[package]
name = "litesvm-fixture"
description = "Fixture-based testing for LiteSVM"
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
litesvm-core = { workspace = true, features = ["persistence-internal"] }
litesvm-fixture-derive.workspace = true
serde_json.workspace = true
solana-account.workspace = true
solana-clock.workspace = true
solana-compute-budget.workspace = true
solana-fee-structure.workspace = true
solana-instruction.workspace = true
solana-instruction-error.workspace = true
solana-message.workspace = true
solana-program-error.workspace = true
solana-program-option.workspace = true
solana-program-pack.workspace = true
solana-pubkey = { workspace = true, features = ["curve25519"] }
solana-rent.workspace = true
solana-sdk-ids.workspace = true
solana-signature.workspace = true
solana-transaction.workspace = true
solana-transaction-error.workspace = true
spl-token = { workspace = true, features = ["no-entrypoint"] }
thiserror.workspace = true
ureq = { workspace = true, features = ["tls"] }
wincode = { workspace = true, features = ["derive"] }

[lints]
workspace = true
