/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class CompiledInstruction {
  constructor(programIdIndex: number, accounts: Uint8Array, data: Uint8Array)
  get programIdIndex(): number
  get accounts(): Uint8Array
  get data(): Uint8Array
}
export declare class InnerInstruction { }
export declare class TransactionMetadata { }
export declare class FailedTransactionMetadata { }
export declare class Account {
  constructor(lamports: bigint, data: Uint8Array, owner: Uint8Array, executable: boolean, rentEpoch: bigint)
  get lamports(): bigint
  get data(): Uint8Array
  get owner(): Uint8Array
  get executable(): boolean
  get rentEpoch(): bigint
}
export type LiteSVM = LiteSvm
export declare class LiteSvm {
  /** Creates the basic test environment. */
  constructor()
  /** Sets all information associated with the account of the provided pubkey. */
  setAccount(pubkey: Uint8Array, data: Account): void
  /** Gets the balance of the provided account pubkey. */
  getBalance(pubkey: Uint8Array): bigint | null
  /** Gets the latest blockhash. */
  latestBlockhash(): string
}
