use {
    crate::LiteSVM,
    jupnet_sdk::{bpf_loader, bpf_loader_deprecated, bpf_loader_upgradeable, pubkey},
};

pub fn load_default_programs(svm: &mut LiteSVM) {
    svm.add_program_preverified(
        pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
        include_bytes!("elf/jpl_associated_token_account.so"),
        &bpf_loader::id(),
    )
    .unwrap();
    svm.add_program_preverified(
        pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"),
        include_bytes!("elf/jpl_token.so"),
        &bpf_loader::id(),
    )
    .unwrap();
    svm.add_program_preverified(
        pubkey!("Memo1UhkJRfHyvLMcVucJwxXeuD728EqVDDwQDxFMNo"),
        include_bytes!("elf/jpl_memo.so"),
        &bpf_loader_deprecated::id(),
    )
    .unwrap();
    svm.add_program_preverified(
        pubkey!("MemoSq4gqABAXKb96qnH8TysNcWxMyWCqXgDLGmfcHr"),
        include_bytes!("elf/jpl_memo.so"),
        &bpf_loader::id(),
    )
    .unwrap();
    svm.add_program_preverified(
        pubkey!("noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"),
        include_bytes!("elf/jpl_noop.so"),
        &bpf_loader::id(),
    )
    .unwrap();
    svm.add_program_preverified(
        pubkey!("namesLPneVptA9Z5rqUDD9tMTWEJwofgaYwp8cawRkX"),
        include_bytes!("elf/jpl_name_service.so"),
        &bpf_loader::id(),
    )
    .unwrap();
    svm.add_program_preverified(
        pubkey!("Tokenis9xgQh7yMRbNBnV6uFq7LANbuZJwebxWBWixf"),
        include_bytes!("elf/jpl_token_2022.so"),
        &bpf_loader_upgradeable::id(),
    )
    .unwrap();
    svm.add_program_preverified(
        pubkey!("Jupnetopen1DRegistry11111111111111111111111"),
        include_bytes!("elf/jupnet_openid_registry_program.so"),
        &bpf_loader_upgradeable::id(),
    )
    .unwrap();
    svm.add_program_preverified(
        pubkey!("JupnetUser111111111111111111111111111111111"),
        include_bytes!("elf/jupnet_user_bpf_program.so"),
        &bpf_loader_upgradeable::id(),
    )
    .unwrap();
}
