/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ComputeBudget {
  constructor()
  get computeUnitLimit(): bigint
  set computeUnitLimit(limit: bigint)
  set log64Units(val: bigint)
  get log64Units(): bigint
  set createProgramAddressUnits(val: bigint)
  get createProgramAddressUnits(): bigint
  set invokeUnits(val: bigint)
  get invokeUnits(): bigint
  set maxInstructionStackDepth(val: bigint)
  get maxInstructionStackDepth(): bigint
  set maxInstructionTraceLength(val: bigint)
  get maxInstructionTraceLength(): bigint
  set sha256BaseCost(val: bigint)
  get sha256BaseCost(): bigint
  set sha256ByteCost(val: bigint)
  get sha256ByteCost(): bigint
  set sha256MaxSlices(val: bigint)
  get sha256MaxSlices(): bigint
  set maxCallDepth(val: bigint)
  get maxCallDepth(): bigint
  set stackFrameSize(val: bigint)
  get stackFrameSize(): bigint
  set logPubkeyUnits(val: bigint)
  get logPubkeyUnits(): bigint
  set maxCpiInstructionSize(val: bigint)
  get maxCpiInstructionSize(): bigint
  set cpiBytesPerUnit(val: bigint)
  get cpiBytesPerUnit(): bigint
  set sysvarBaseCost(val: bigint)
  get sysvarBaseCost(): bigint
  set secp256K1RecoverCost(val: bigint)
  get secp256K1RecoverCost(): bigint
  set syscallBaseCost(val: bigint)
  get syscallBaseCost(): bigint
  set curve25519EdwardsValidatePointCost(val: bigint)
  get curve25519EdwardsValidatePointCost(): bigint
  set curve25519EdwardsAddCost(val: bigint)
  get curve25519EdwardsAddCost(): bigint
  set curve25519EdwardsSubtractCost(val: bigint)
  get curve25519EdwardsSubtractCost(): bigint
  set curve25519EdwardsMultiplyCost(val: bigint)
  get curve25519EdwardsMultiplyCost(): bigint
  set curve25519EdwardsMsmBaseCost(val: bigint)
  get curve25519EdwardsMsmBaseCost(): bigint
  set curve25519EdwardsMsmIncrementalCost(val: bigint)
  get curve25519EdwardsMsmIncrementalCost(): bigint
  set curve25519RistrettoValidatePointCost(val: bigint)
  get curve25519RistrettoValidatePointCost(): bigint
  set curve25519RistrettoAddCost(val: bigint)
  get curve25519RistrettoAddCost(): bigint
  set curve25519RistrettoSubtractCost(val: bigint)
  get curve25519RistrettoSubtractCost(): bigint
  set curve25519RistrettoMultiplyCost(val: bigint)
  get curve25519RistrettoMultiplyCost(): bigint
  set curve25519RistrettoMsmBaseCost(val: bigint)
  get curve25519RistrettoMsmBaseCost(): bigint
  set curve25519RistrettoMsmIncrementalCost(val: bigint)
  get curve25519RistrettoMsmIncrementalCost(): bigint
  set heapSize(val: number)
  get heapSize(): number
  set heapCost(val: bigint)
  get heapCost(): bigint
  set memOpBaseCost(val: bigint)
  get memOpBaseCost(): bigint
  set altBn128AdditionCost(val: bigint)
  get altBn128AdditionCost(): bigint
  set altBn128MultiplicationCost(val: bigint)
  get altBn128MultiplicationCost(): bigint
  set altBn128PairingOnePairCostFirst(val: bigint)
  get altBn128PairingOnePairCostFirst(): bigint
  set altBn128PairingOnePairCostOther(val: bigint)
  get altBn128PairingOnePairCostOther(): bigint
  set bigModularExponentiationBaseCost(val: bigint)
  get bigModularExponentiationBaseCost(): bigint
  set bigModularExponentiationCostDivisor(val: bigint)
  get bigModularExponentiationCostDivisor(): bigint
  set poseidonCostCoefficientA(val: bigint)
  get poseidonCostCoefficientA(): bigint
  set poseidonCostCoefficientC(val: bigint)
  get poseidonCostCoefficientC(): bigint
  set getRemainingComputeUnitsCost(val: bigint)
  get getRemainingComputeUnitsCost(): bigint
  set altBn128G1Compress(val: bigint)
  get altBn128G1Compress(): bigint
  set altBn128G1Decompress(val: bigint)
  get altBn128G1Decompress(): bigint
  set altBn128G2Compress(val: bigint)
  get altBn128G2Compress(): bigint
  set altBn128G2Decompress(val: bigint)
  get altBn128G2Decompress(): bigint
}
export declare class CompiledInstruction {
  constructor(programIdIndex: number, accounts: Uint8Array, data: Uint8Array)
  programIdIndex(): number
  accounts(): Uint8Array
  data(): Uint8Array
}
export declare class InnerInstruction {
  instruction(): CompiledInstruction
  stackHeight(): number
}
export declare class TransactionReturnData {
  programId(): Uint8Array
  data(): Uint8Array
}
export declare class FeatureSet {
  static default(): FeatureSet
  static allEnabled(): FeatureSet
  isActive(featureId: Uint8Array): boolean
  activatedSlot(featureId: Uint8Array): bigint | null
  /** For internal use only. */
  toInternal(): Array<ActiveFeatureInternal>
}
/** For internal use only */
export declare class ActiveFeatureInternal {
  address: Uint8Array
  slot: bigint
}
export declare class TransactionMetadata {
  signature(): Uint8Array
  logs(): Array<string>
  innerInstructions(): Array<Array<InnerInstruction>>
  computeUnitsConsumed(): bigint
  returnData(): TransactionReturnData
}
export declare class FailedTransactionMetadata {
  err(): string
  meta(): TransactionMetadata
}
export declare class AddressAndAccount {
  address: Uint8Array
  account(): Account
}
export declare class SimulatedTransactionInfo {
  meta(): TransactionMetadata
  postAccounts(): Array<AddressAndAccount>
}
export declare class Account {
  constructor(lamports: bigint, data: Uint8Array, owner: Uint8Array, executable: boolean, rentEpoch: bigint)
  lamports(): bigint
  data(): Uint8Array
  owner(): Uint8Array
  executable(): boolean
  rentEpoch(): bigint
}
export declare class LiteSvm {
  /** Creates the basic test environment. */
  constructor()
  static default(): LiteSvm
  /** Sets the compute budget. */
  setComputeBudget(computeUnitLimit: bigint, log64Units: bigint, createProgramAddressUnits: bigint, invokeUnits: bigint, maxInstructionStackDepth: bigint, maxInstructionTraceLength: bigint, sha256BaseCost: bigint, sha256ByteCost: bigint, sha256MaxSlices: bigint, maxCallDepth: bigint, stackFrameSize: bigint, logPubkeyUnits: bigint, maxCpiInstructionSize: bigint, cpiBytesPerUnit: bigint, sysvarBaseCost: bigint, secp256K1RecoverCost: bigint, syscallBaseCost: bigint, curve25519EdwardsValidatePointCost: bigint, curve25519EdwardsAddCost: bigint, curve25519EdwardsSubtractCost: bigint, curve25519EdwardsMultiplyCost: bigint, curve25519EdwardsMsmBaseCost: bigint, curve25519EdwardsMsmIncrementalCost: bigint, curve25519RistrettoValidatePointCost: bigint, curve25519RistrettoAddCost: bigint, curve25519RistrettoSubtractCost: bigint, curve25519RistrettoMultiplyCost: bigint, curve25519RistrettoMsmBaseCost: bigint, curve25519RistrettoMsmIncrementalCost: bigint, heapSize: number, heapCost: bigint, memOpBaseCost: bigint, altBn128AdditionCost: bigint, altBn128MultiplicationCost: bigint, altBn128PairingOnePairCostFirst: bigint, altBn128PairingOnePairCostOther: bigint, bigModularExponentiationBaseCost: bigint, bigModularExponentiationCostDivisor: bigint, poseidonCostCoefficientA: bigint, poseidonCostCoefficientC: bigint, getRemainingComputeUnitsCost: bigint, altBn128G1Compress: bigint, altBn128G1Decompress: bigint, altBn128G2Compress: bigint, altBn128G2Decompress: bigint): void
  /** Enables or disables sigverify */
  setSigverify(sigverify: boolean): void
  /** Enables or disables the blockhash check */
  setBlockhashCheck(check: boolean): void
  /** Includes the default sysvars */
  setSysvars(): void
  /** Changes the default builtins */
  setBuiltins(featureSet?: Array<[Uint8Array, bigint]> | undefined | null): void
  /** Changes the initial lamports in LiteSVM's airdrop account */
  setLamports(lamports: bigint): void
  /** Includes the standard SPL programs */
  setSplPrograms(): void
  /**
   * Changes the capacity of the transaction history.
   * Set this to 0 to disable transaction history and allow duplicate transactions.
   */
  setTransactionHistory(capacity: bigint): void
  setLogBytesLimit(limit?: bigint | undefined | null): void
  setPrecompiles(featureSet?: Array<[Uint8Array, bigint]> | undefined | null): void
  /** Returns minimum balance required to make an account with specified data length rent exempt. */
  minimumBalanceForRentExemption(dataLen: bigint): bigint
  /** Returns all information associated with the account of the provided pubkey. */
  getAccount(pubkey: Uint8Array): Account | null
  /** Sets all information associated with the account of the provided pubkey. */
  setAccount(pubkey: Uint8Array, data: Account): void
  /** Gets the balance of the provided account pubkey. */
  getBalance(pubkey: Uint8Array): bigint | null
  /** Gets the latest blockhash. */
  latestBlockhash(): string
  /** Gets a transaction from the transaction history. */
  getTransaction(signature: Uint8Array): TransactionMetadata | FailedTransactionMetadata | null
  /** Airdrops the account with the lamports specified. */
  airdrop(pubkey: Uint8Array, lamports: bigint): TransactionMetadata | FailedTransactionMetadata | null
  /** Adds am SBF program to the test environment from the file specified. */
  addProgramFromFile(programId: Uint8Array, path: string): void
  /** Adds am SBF program to the test environment. */
  addProgram(programId: Uint8Array, programBytes: Uint8Array): void
  sendLegacyTransaction(txBytes: Uint8Array): TransactionMetadata | FailedTransactionMetadata
  sendVersionedTransaction(txBytes: Uint8Array): TransactionMetadata | FailedTransactionMetadata
  simulateLegacyTransaction(txBytes: Uint8Array): SimulatedTransactionInfo | FailedTransactionMetadata
  simulateVersionedTransaction(txBytes: Uint8Array): SimulatedTransactionInfo | FailedTransactionMetadata
  /** Expires the current blockhash */
  expireBlockhash(): void
  /** Warps the clock to the specified slot */
  warpToSlot(slot: bigint): void
  getComputeBudget(): ComputeBudget | null
}
