name: go-lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crates/go-litesvm
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache-dependency-path: crates/go-litesvm/go.sum
      - name: Rustup install
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
      - name: Lint rust
        run: cargo clippy
      - name: gofmt
        run: |
          out=$(gofmt -l .)
          if [ -n "$out" ]; then
            echo "The following files need to be formatted:"
            echo "$out"
            exit 1
          fi
      - name: go vet
        run: go vet ./...
