name: node-docs-check

on:
  push:
    branches: [master]
    paths-ignore:
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
  pull_request:
    branches: [master]
    paths-ignore:
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: corepack enable && yarn install --immutable
      - name: Build with VitePress
        run: yarn workspace litesvm predocs && yarn workspace litesvm docs:build
