name: node-lint
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    paths-ignore:
      - '**/*.md'
      - LICENSE
      - '**/*.gitignore'
      - .editorconfig
      - crates/node-litesvm/docs/**
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Install dependencies
        run: corepack enable && yarn install --immutable
      - name: Check Rust formatting
        run: cargo fmt --all -- --check
      - name: Lint Rust core
        run: yarn workspace litesvm-core lint
      - name: Lint Kit wrapper
        run: yarn workspace litesvm lint:js
      - name: Lint Web3.js wrapper
        run: yarn workspace litesvm-web3js lint
