name: release NodeJS

on:
  push:
    tags:
      - "node-v[0-9]+.[0-9]+.[0-9]+"
      - "node-v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          check-latest: true
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install dependencies
        run: corepack enable && yarn install --immutable
      - name: Create native package directories
        run: yarn workspace litesvm-core napi create-npm-dirs
      - name: Download all native artifacts
        uses: dawidd6/action-download-artifact@v11
        with:
          workflow: node-build.yml
          path: crates/node-litesvm-core/artifacts
      - name: Move native artifacts
        run: yarn workspace litesvm-core artifacts
      - name: Build Kit wrapper
        run: yarn workspace litesvm build
      - name: List native packages
        run: ls -R crates/node-litesvm-core/npm
      - name: Publish core and Kit wrapper
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          TAG=latest
          [[ "$GITHUB_REF_NAME" == *-rc.* ]] && TAG=next
          yarn workspace litesvm-core npm publish --access public --tag "$TAG"
          yarn workspace litesvm npm publish --access public --tag "$TAG"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
